package msgs

//Tipovi poruka
const (
	TypeAppVersion          = "app_version"
	TypeMojiListici         = "moji_listici"
	TypeMojiListiciTip      = "moji_listici_tip"
	TypeSync                = "sync"
	TypeListic              = "listic"
	TypeDodajListic         = "dodaj_listic"
	TypeSubscribe           = "subscribe"
	TypeLiveStream          = "live_stream"
	TypeLiveStreamMobile    = "live_stream_mobile"
	TypeListiciIsplati      = "listici/isplati"
	TypeListiciDodaj        = "listici/dodaj"
	TypeIsplataStorno       = "isplata/storno"
	TypeIsplataPoslovnica   = "racun/isplata_poslovnica"
	TypeIsplataRacun        = "racun/isplata_racun"
	TypeIsplataSkrill       = "racun/pripremi_gateway_isplatu"
	TypeObrisiRacun         = "racun/obrisi_racun"
	TypeUplatiNaRacun       = "racun/pripremi_gateway_uplatu"
	TypePromijeniLozinku    = "racun/promijeni_lozinku"
	TypePromijeniEmail      = "racun/promijeni_email"
	TypePromijeniPodatke    = "racun/promijeni_osobne_podatke"
	TypeAktivirajEmail      = "racun/aktiviraj_email"
	TypeProvjeraUplate      = "racun/provjera_uplate"
	TypeExtraPodaci         = "racun/extra_podaci"
	TypeSamoogranicenjeSet  = "samoogranicenje/set"
	TypeSamoogranicenjeDel  = "samoogranicenje/del"
	TypeTransakcije         = "transakcije"
	TypePoruke              = "poruke"
	TypeUvjetiKoristenja    = "gdpr/uvjeti_koristenja"
	TypePostavkePrivatnosti = "gdpr/postavke_privatnosti"
	TypeAircashBon          = "aircash/activate_bon"
	TypeAircashIsplata      = "aircash_isplata/isplati"
	TypeCashVoucherDeposit  = "cashvoucher/deposit"
)
