package msgs

//Tipovi poruka
const (
	TypeAppVersion         = "app_version"
	TypeMojiListici        = "moji_listici"
	TypeSync               = "sync"
	TypeListic             = "listic"
	TypeDodajListic        = "dodaj_listic"
	TypeSubscribe          = "subscribe"
	TypeLiveStream         = "live_stream"
	TypeLiveStreamMobile   = "live_stream_mobile"
	TypeListiciIsplati     = "listici/isplati"
	TypeListiciDodaj       = "listici/dodaj"
	TypeIsplataStorno      = "isplata/storno"
	TypeIsplataPoslovnica  = "isplata/poslovnica"
	TypeIsplataRacun       = "isplata/racun"
	TypeIsplataSkrill      = "isplata/skrill"
	TypeObrisiRacun        = "igraci/obrisi_racun"
	TypeUplatiNaRacun      = "uplata"
	TypePromijeniLozinku   = "promijeni_lozinku"
	TypePromijeniEmail     = "promijeni_email"
	TypePromijeniPodatke   = "promijeni_podatke"
	TypeAktivirajEmail     = "aktiviraj_email"
	TypeProvjeraUplate     = "provjera_uplate"
	TypeSamoogranicenjeSet = "samoogranicenje/set"
	TypeSamoogranicenjeDel = "samoogranicenje/del"
	TypeTransakcije        = "transakcije"
	TypePoruke             = "poruke"

	TypeValidacijaNadimak      = "registracija/validacija/nadimak"
	TypeValidacijaEmail        = "registracija/validacija/email"
	TypeValidacijaOib          = "registracija/validacija/oib"
	TypeValidacijaPunoljetnost = "registracija/validacija/punoljetnost"
	TypeValidacijaKod          = "registracija/validacija/kod"
	TypeValidacijaProvjeriKod  = "registracija/validacija/provjeriKod"
	TypeValidacijaTelefon      = "registracija/validacija/telefon"
)
